/* Fallback copy. The real, unique, owner-focused prose is generated by the
   content workflow and saved to content/generated/<slug>.json. This module
   only guarantees the build renders a coherent page if a generated file is
   missing. It is intentionally generic; do NOT ship it as final marketing copy
   (it is the city-swapped boilerplate the SEO spec warns against). */

export function geoFallback(m) {
  return {
    metaTitle: `${m.city} Vacation Rental Management | Haven`,
    metaDescription: `Full-service vacation rental management in ${m.city}, TN. Haven owners earn more with one flat fee, smart local pricing, and a five-star guest experience. Book a call.`,
    heroEyebrow: "Smoky Mountains property management",
    h1: `Vacation Rental Management in ${m.city}, TN`,
    heroSubhead: `Full-service cabin and vacation rental management for ${m.city} owners, run by a local team that knows this market.`,
    introHeading: `Owning a ${m.city} cabin should not feel like a second job`,
    introParagraphs: [
      `${m.city} is one of the most competitive short-term rental markets in the country, and standing out takes more than a good listing. Pricing, guest communication, cleaning, maintenance, and local compliance all have to run like clockwork, every single day.`,
      `Haven handles all of it for one simple flat fee, so your ${m.city} cabin earns more while you do less.`,
    ],
    snapshotHeading: `The ${m.city} market at a glance`,
    snapshotParagraphs: [
      `Here is how the ${m.city} market looks heading into 2026, and where a local manager makes the difference.`,
    ],
    servicesIntro: `Full-service means we run everything: bookings, pricing, marketing, cleaning, guest communication, maintenance, payouts, and reviews. You get one local point of contact and one flat fee.`,
    whyHeading: `Why ${m.city} owners choose Haven`,
    whyParagraphs: [
      `We are a smaller, local team by design, which means your property gets attention a national manager cannot match.`,
    ],
    regHeading: `${m.city} short-term rental rules, handled for you`,
    regIntro: [
      `Running a legal short-term rental in ${m.city} means permits, inspections, taxes, and zoning. Here is the plain-English version, and how Haven takes it off your plate.`,
    ],
    regClosing: `Haven manages every piece of this for our owners, so your ${m.city} cabin stays compliant and earning.`,
    processIntro: `Switching to Haven is simple, and we handle the heavy lifting.`,
    faqs: (m.regItems || []).slice(0, 6).map((r) => ({
      q: `What should ${m.city} owners know about ${r.title.toLowerCase()}?`,
      a: [r.body],
    })),
    testimonial: {
      quote: `Switching to Haven was the best decision we made for our cabin. Bookings are up, the reviews are glowing, and we finally stopped worrying about it.`,
      name: "Haven cabin owner",
      role: "Owner",
      location: `${m.city}, TN`,
    },
    closingHeading: "Let's talk",
    closingParagraph: `Book a quick call and we will show you what your ${m.city} property can earn with Haven.`,
    crossLinkBlurb: `Local, full-service vacation rental management for ${m.city} cabin owners.`,
  };
}

export function homeFallback() {
  return {
    metaTitle: "Smoky Mountain Vacation Rental Management | Haven",
    metaDescription: "Haven is a local, full-service vacation rental management company in the Smoky Mountains. One flat fee, smart human pricing, and a five-star guest experience. Book a call.",
    heroEyebrow: "Smoky Mountain vacation rental management",
    h1: "Your Smoky Mountain cabin, managed to earn more",
    heroSubhead: "Haven is a local, full-service property management team for cabin owners across Gatlinburg, Pigeon Forge, Sevierville, and Wears Valley.",
    introHeading: "Local management that treats your cabin like our own",
    introParagraphs: [
      "Most owners do not want a second job. They want their cabin to earn well and run smoothly without the daily firefighting. That is exactly what Haven delivers.",
      "We are based right here in the Smokies, we charge one simple flat fee, and we obsess over the guest experience that drives your reviews, your ranking, and your revenue.",
    ],
    servicesIntro: "From the first inquiry to the final review, one local team handles it all.",
    valueHeading: "Smaller, local, and relentlessly focused on your return",
    valueParagraphs: [
      "We deliberately manage a select group of homes well rather than thousands poorly. The result is higher occupancy, stronger reviews, and net revenue that runs ahead of the market.",
    ],
    faqs: [],
    closingHeading: "Ready when you are",
    closingParagraph: "Book a no-pressure call and we will show you what your Smoky Mountain cabin can earn with Haven.",
  };
}

export function hubFallback() {
  return {
    metaTitle: "Smoky Mountain Property Management | Haven Vacation Rentals",
    metaDescription: "Full-service Smoky Mountain vacation rental management for cabin owners in Sevier County. One flat fee, local pricing, and a five-star guest experience. Book a call.",
    heroEyebrow: "Smoky Mountain property management",
    h1: "Full-Service Vacation Rental Management in the Smoky Mountains",
    heroSubhead: "One local team manages your cabin end to end across Sevier County, for one simple flat fee.",
    introHeading: "Property management built around your net revenue",
    introParagraphs: [
      "Haven manages cabins and vacation rentals across the Smoky Mountains for owners who want more revenue and less hassle. We handle bookings, pricing, marketing, cleaning, guests, maintenance, and compliance, all for one flat fee.",
    ],
    servicesIntro: "Full-service means truly everything. Here is what we take off your plate.",
    servicesDetail: [
      "Every service above is included in one flat management fee, with no hidden booking-fee markups and no surprise charges on your statement.",
    ],
    whyHeading: "Why Smoky Mountain owners choose Haven",
    whyParagraphs: [
      "We are local, we are flat-fee, and we are guest-obsessed. That combination is how Haven owners run ahead of the market.",
    ],
    areasIntro: "Pick your market for local rates, regulations, and what your cabin can earn.",
    areasNote: "We also manage cabins in Townsend and around Knoxville. If your property is anywhere in or near Sevier County, we would love to talk.",
    feesHeading: "How our fees work, and what owners earn",
    feesParagraphs: [
      "Haven charges one simple flat management fee. There are no hidden booking fees, no markups on cleaning, and no nickel-and-diming. You always know what you pay and what you earn.",
      "Haven owners average around 70% occupancy versus a market average near 55%, and run roughly 30% ahead of the market on revenue. Confirm current figures with our team for your specific property.",
    ],
    faqs: [],
    closingHeading: "Ready when you are",
    closingParagraph: "Book a no-pressure call and we will show you what your cabin can earn with Haven.",
  };
}
